services:
  - type: web
    name: rxnorm-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        fromService:
          type: web
          name: rxnorm-api
          property: port
      - key: DATABASE_URL
        value: postgresql://postgres.ynbsbpmyzubwkmfgdzes:Sanjanadalal11@aws-1-us-east-1.pooler.supabase.com:6543/postgres
